// Auto-generated by generate_overlay.py
// DO NOT EDIT — regenerate from the trained model instead.

`ifndef GLOBALS_SV
`define GLOBALS_SV

localparam NET_INPUTS     = 400;
localparam L0_NEURONS    = 2000;
localparam L1_NEURONS    = 2000;
localparam CLASS_OUTS     = 200;
localparam NET_OUTPUT_BITS = 4;
localparam TOTAL_GATES    = 4000;
localparam L0_GATE_BASE = 0;
localparam L1_GATE_BASE = 2000;
localparam GATE_SEL_W     = $clog2(TOTAL_GATES);

`endif // GLOBALS_SV
