// Auto-generated by generate_overlay.py
// Reconfigurable LLNN Overlay — Top Module

`include "Globals.sv"

module top (
	input  logic        clk,
	input  logic        rst_n,

	// AXI-Lite Slave (directly exposed for block design)
	input  logic [15:0] S_AXI_AWADDR,
	input  logic        S_AXI_AWVALID,
	output logic        S_AXI_AWREADY,
	input  logic [31:0] S_AXI_WDATA,
	input  logic [3:0]  S_AXI_WSTRB,
	input  logic        S_AXI_WVALID,
	output logic        S_AXI_WREADY,
	output logic [1:0]  S_AXI_BRESP,
	output logic        S_AXI_BVALID,
	input  logic        S_AXI_BREADY,
	input  logic [15:0] S_AXI_ARADDR,
	input  logic        S_AXI_ARVALID,
	output logic        S_AXI_ARREADY,
	output logic [31:0] S_AXI_RDATA,
	output logic [1:0]  S_AXI_RRESP,
	output logic        S_AXI_RVALID,
	input  logic        S_AXI_RREADY
);

	// ---- Internal wires ----
	logic [NET_INPUTS-1:0] NET_I;
	logic [3:0] NET_O;
	logic [GATE_SEL_W-1:0] cfg_gate_sel;
	logic cfg_ce, cfg_data;

	logic [L0_NEURONS-1:0] F_L0;
	logic [L1_NEURONS-1:0] F_L1;
	logic [$clog2(CLASS_OUTS+1)-1:0] C0;
	logic [$clog2(CLASS_OUTS+1)-1:0] C_reg0;
	logic [$clog2(CLASS_OUTS+1)-1:0] C1;
	logic [$clog2(CLASS_OUTS+1)-1:0] C_reg1;
	logic [$clog2(CLASS_OUTS+1)-1:0] C2;
	logic [$clog2(CLASS_OUTS+1)-1:0] C_reg2;
	logic [$clog2(CLASS_OUTS+1)-1:0] C3;
	logic [$clog2(CLASS_OUTS+1)-1:0] C_reg3;
	logic [$clog2(CLASS_OUTS+1)-1:0] C4;
	logic [$clog2(CLASS_OUTS+1)-1:0] C_reg4;
	logic [$clog2(CLASS_OUTS+1)-1:0] C5;
	logic [$clog2(CLASS_OUTS+1)-1:0] C_reg5;
	logic [$clog2(CLASS_OUTS+1)-1:0] C6;
	logic [$clog2(CLASS_OUTS+1)-1:0] C_reg6;
	logic [$clog2(CLASS_OUTS+1)-1:0] C7;
	logic [$clog2(CLASS_OUTS+1)-1:0] C_reg7;
	logic [$clog2(CLASS_OUTS+1)-1:0] C8;
	logic [$clog2(CLASS_OUTS+1)-1:0] C_reg8;
	logic [$clog2(CLASS_OUTS+1)-1:0] C9;
	logic [$clog2(CLASS_OUTS+1)-1:0] C_reg9;
	logic [$clog2(CLASS_OUTS+1)-1:0] max0;
	logic [$clog2(CLASS_OUTS+1)-1:0] max1;
	logic [$clog2(CLASS_OUTS+1)-1:0] max2;
	logic [$clog2(CLASS_OUTS+1)-1:0] max3;
	logic [$clog2(CLASS_OUTS+1)-1:0] max4;
	logic [$clog2(CLASS_OUTS+1)-1:0] max5;
	logic [$clog2(CLASS_OUTS+1)-1:0] max6;
	logic [$clog2(CLASS_OUTS+1)-1:0] max7;
	logic idx0;
	logic idx1;
	logic idx2;
	logic idx3;
	logic idx4;
	logic idx5;
	logic idx6;
	logic idx7;
	logic idx8;
	// ---- Pipeline Registers for Output Header ----
	logic [L1_NEURONS-1:0] F_L_last_reg;
	always_ff @(posedge clk) begin
		F_L_last_reg <= F_L1;
		C_reg0 <= C0;
		C_reg1 <= C1;
		C_reg2 <= C2;
		C_reg3 <= C3;
		C_reg4 <= C4;
		C_reg5 <= C5;
		C_reg6 <= C6;
		C_reg7 <= C7;
		C_reg8 <= C8;
		C_reg9 <= C9;
	end

	// ---- AXI Configuration Controller ----
	axi_lut_ctrl #(
		.TOTAL_GATES  (TOTAL_GATES),
		.NET_INPUTS   (NET_INPUTS),
		.NET_OUTPUTS  (4)
	) u_axi_ctrl (
		.S_AXI_ACLK    (clk),
		.S_AXI_ARESETN (rst_n),
		.S_AXI_AWADDR     (S_AXI_AWADDR),
		.S_AXI_AWVALID    (S_AXI_AWVALID),
		.S_AXI_AWREADY    (S_AXI_AWREADY),
		.S_AXI_WDATA      (S_AXI_WDATA),
		.S_AXI_WSTRB      (S_AXI_WSTRB),
		.S_AXI_WVALID     (S_AXI_WVALID),
		.S_AXI_WREADY     (S_AXI_WREADY),
		.S_AXI_BRESP      (S_AXI_BRESP),
		.S_AXI_BVALID     (S_AXI_BVALID),
		.S_AXI_BREADY     (S_AXI_BREADY),
		.S_AXI_ARADDR     (S_AXI_ARADDR),
		.S_AXI_ARVALID    (S_AXI_ARVALID),
		.S_AXI_ARREADY    (S_AXI_ARREADY),
		.S_AXI_RDATA      (S_AXI_RDATA),
		.S_AXI_RRESP      (S_AXI_RRESP),
		.S_AXI_RVALID     (S_AXI_RVALID),
		.S_AXI_RREADY     (S_AXI_RREADY),
		.cfg_gate_sel  (cfg_gate_sel),
		.cfg_ce        (cfg_ce),
		.cfg_data      (cfg_data),
		.net_i         (NET_I),
		.net_o         (NET_O)
	);

	// ---- Inference Layers ----
	layer0 L0 (
		.clk          (clk),
		.in           (NET_I),
		.out          (F_L0),
		.cfg_gate_sel (cfg_gate_sel),
		.cfg_ce       (cfg_ce),
		.cfg_data     (cfg_data)
	);

	layer1 L1 (
		.clk          (clk),
		.in           (F_L0),
		.out          (F_L1),
		.cfg_gate_sel (cfg_gate_sel),
		.cfg_ce       (cfg_ce),
		.cfg_data     (cfg_data)
	);

	// ---- Popcount per class ----
	function automatic [$clog2(CLASS_OUTS+1)-1:0] popcount;
		input [199:0] v;
		integer i;
		begin
			popcount = 0;
			for (i = 0; i < 200; i = i + 1)
				popcount = popcount + v[i];
		end
	endfunction

	assign C9 = popcount(F_L_last_reg[1999:1800]);
	assign C8 = popcount(F_L_last_reg[1799:1600]);
	assign C7 = popcount(F_L_last_reg[1599:1400]);
	assign C6 = popcount(F_L_last_reg[1399:1200]);
	assign C5 = popcount(F_L_last_reg[1199:1000]);
	assign C4 = popcount(F_L_last_reg[999:800]);
	assign C3 = popcount(F_L_last_reg[799:600]);
	assign C2 = popcount(F_L_last_reg[599:400]);
	assign C1 = popcount(F_L_last_reg[399:200]);
	assign C0 = popcount(F_L_last_reg[199:0]);

	// ---- Comparator reduction chain ----
	comparator CMP0 (
		.in1 (C_reg0),
		.in2 (C_reg1),
		.max (max0),
		.idx (idx0)
	);

	comparator CMP1 (
		.in1 (max0),
		.in2 (C_reg2),
		.max (max1),
		.idx (idx1)
	);

	comparator CMP2 (
		.in1 (max1),
		.in2 (C_reg3),
		.max (max2),
		.idx (idx2)
	);

	comparator CMP3 (
		.in1 (max2),
		.in2 (C_reg4),
		.max (max3),
		.idx (idx3)
	);

	comparator CMP4 (
		.in1 (max3),
		.in2 (C_reg5),
		.max (max4),
		.idx (idx4)
	);

	comparator CMP5 (
		.in1 (max4),
		.in2 (C_reg6),
		.max (max5),
		.idx (idx5)
	);

	comparator CMP6 (
		.in1 (max5),
		.in2 (C_reg7),
		.max (max6),
		.idx (idx6)
	);

	comparator CMP7 (
		.in1 (max6),
		.in2 (C_reg8),
		.max (max7),
		.idx (idx7)
	);

	comparator CMP8 (
		.in1 (max7),
		.in2 (C_reg9),
		.max (),
		.idx (idx8)
	);

	// ---- Output encoding (argmax) ----
	always_comb begin
		NET_O = 4'b1111;
		if (idx0 == 1'b0 && idx1 == 1'b0 && idx2 == 1'b0 && idx3 == 1'b0 && idx4 == 1'b0 && idx5 == 1'b0 && idx6 == 1'b0 && idx7 == 1'b0 && idx8 == 1'b0) NET_O = 4'b0000;
		if (idx0 == 1'b1 && idx1 == 1'b0 && idx2 == 1'b0 && idx3 == 1'b0 && idx4 == 1'b0 && idx5 == 1'b0 && idx6 == 1'b0 && idx7 == 1'b0 && idx8 == 1'b0) NET_O = 4'b0001;
		if (idx1 == 1'b1 && idx2 == 1'b0 && idx3 == 1'b0 && idx4 == 1'b0 && idx5 == 1'b0 && idx6 == 1'b0 && idx7 == 1'b0 && idx8 == 1'b0) NET_O = 4'b0010;
		if (idx2 == 1'b1 && idx3 == 1'b0 && idx4 == 1'b0 && idx5 == 1'b0 && idx6 == 1'b0 && idx7 == 1'b0 && idx8 == 1'b0) NET_O = 4'b0011;
		if (idx3 == 1'b1 && idx4 == 1'b0 && idx5 == 1'b0 && idx6 == 1'b0 && idx7 == 1'b0 && idx8 == 1'b0) NET_O = 4'b0100;
		if (idx4 == 1'b1 && idx5 == 1'b0 && idx6 == 1'b0 && idx7 == 1'b0 && idx8 == 1'b0) NET_O = 4'b0101;
		if (idx5 == 1'b1 && idx6 == 1'b0 && idx7 == 1'b0 && idx8 == 1'b0) NET_O = 4'b0110;
		if (idx6 == 1'b1 && idx7 == 1'b0 && idx8 == 1'b0) NET_O = 4'b0111;
		if (idx7 == 1'b1 && idx8 == 1'b0) NET_O = 4'b1000;
		if (idx8 == 1'b1) NET_O = 4'b1001;
	end

endmodule : top
